name = "xau-ai-signal-genz"
main = "src/index.js"
compatibility_date = "2026-05-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "SIGNALS_KV"
id = "GANTI_DENGAN_KV_NAMESPACE_ID"
preview_id = "GANTI_DENGAN_PREVIEW_KV_NAMESPACE_ID"
